import React from 'react'
import vid from "../assets/IAVID.mp4"
import { FiPlay } from "react-icons/fi";
import { Link } from 'react-router-dom';


const PreSection = () => {
    return (

        <section className='flex max-md:flex-col min-w-96 w-11/12  m-auto my-20 bg-slate-100 dark:bg-slate-300 rounded-2xl shadow-lg '>
            <article className='w-1/2 p-8 max-md:w-full max-md:h-1/2 '>
                <h1 className='text-3xl font-bold m-4 w-11/12'>Get Yourself An <span className='text-purple-700'>Easy Diagnostic</span> For <span className='text-purple-700'>Free</span> Right Now!</h1>
                <div className='text-xl p-8 my-5 w-11/12'>
                    <p>Designed for easy interaction and accessibility, they bridge the gap between patients and medical insights, ultimately improving healthcare outcomes.
                    </p>
                </div>

                <div className='grid grid-rows-2 p-8 gap-2'>
                    <p className=' flex text-xl max-sm:text-sm  gap-4  font-semibold '><FiPlay className='w-fit text-3xl max-sm:text-sm text-purple-800' /> Get an Easy Diagnostic Generated By AI.</p>
                    <p className=' flex text-xl  max-sm:text-sm gap-4 font-semibold'><FiPlay className='w-fit text-3xl max-sm:text-sm text-purple-800' />Get a specific Recommendations</p>
                </div>

                <div className='mx-16 mt-2 '>
                    <Link to="/Home"><button className='text-white font-semibold hover:bg-purple-500 border-2 m-4 text-2xl max-sm:text-sm hover:outline-purple-900 bg-purple-600 rounded-xl px-6 py-4 '>Get Started</button></Link>
                </div>

            </article>
            <article className='w-1/2 max-md:w-full max-md:h-1/2 p-2  flex bg-transparent  justify-center items-center'>
                <div className='w-fit h-fit bg-slate-100 p-6 rounded-3xl shadow-2xl dark:bg-slate-300  shadow-gray-700 dark:shadow-slate-900' >
                    <div className='w-fit h-fit bg-purple-500 p-4 rounded-3xl '>
                        <video className='rounded-3xl' src={vid} controls  autoPlay muted  loop ></video>
                    </div>
                </div>
            </article>

        </section>
    )
}

export default PreSection
